from __future__ import annotations

from textwrap import dedent

import pytest
from pants.backend.java.target_types import JavaSourcesGeneratorTarget
from pants.core.goals.package import rules as package_rules
from pants.core.goals.test import TestResult
from pants.core.goals.test import rules as test_goal_rules
from pants.core.target_types import FileTarget, FilesGeneratorTarget
from pants.core.util_rules import config_files, source_files, stripped_source_files, system_binaries
from pants.engine.addresses import Address
from pants.engine.rules import QueryRule
from pants.jvm import classpath, jvm_common, non_jvm_dependencies
from pants.jvm.goals import lockfile
from pants.jvm.resolve.coursier_fetch import rules as coursier_fetch_rules
from pants.jvm.resolve.coursier_setup import rules as coursier_setup_rules
from pants.jvm.target_types import JvmArtifactTarget
from pants.jvm.util_rules import rules as jdk_util_rules
from pants.testutil.rule_runner import PYTHON_BOOTSTRAP_ENV, RuleRunner
from pants_backend_clojure import compile_clj
from pants_backend_clojure.goals.test import ClojureTestFieldSet, ClojureTestRequest
from pants_backend_clojure.goals.test import rules as test_runner_rules
from pants_backend_clojure.target_types import (
    ClojureSourcesGeneratorTarget,
    ClojureSourceTarget,
    ClojureTestsGeneratorTarget,
    ClojureTestTarget,
)
from pants_backend_clojure.target_types import rules as target_types_rules
from tests.clojure_test_fixtures import CLOJURE_3RDPARTY_BUILD, CLOJURE_LOCKFILE


@pytest.fixture
def rule_runner() -> RuleRunner:
    rule_runner = RuleRunner(
        preserve_tmpdirs=True,
        rules=[
            *classpath.rules(),
            *compile_clj.rules(),
            *config_files.rules(),
            *coursier_fetch_rules(),
            *coursier_setup_rules(),
            *jdk_util_rules(),
            *jvm_common.rules(),
            *non_jvm_dependencies.rules(),
            *source_files.rules(),
            *stripped_source_files.rules(),
            *system_binaries.rules(),
            *target_types_rules(),
            *test_runner_rules(),
            *test_goal_rules(),
            *package_rules(),
            *lockfile.rules(),
            QueryRule(TestResult, [ClojureTestRequest.Batch]),
        ],
        target_types=[
            ClojureSourceTarget,
            ClojureSourcesGeneratorTarget,
            ClojureTestTarget,
            ClojureTestsGeneratorTarget,
            JvmArtifactTarget,
            JavaSourcesGeneratorTarget,
            FileTarget,
            FilesGeneratorTarget,
        ],
    )
    return rule_runner


_JVM_RESOLVES = {
    "jvm-default": "3rdparty/jvm/default.lock",
}


def run_clojure_test(
    rule_runner: RuleRunner,
    target_name: str,
    relative_file_path: str,
    *,
    spec_path: str = "",
    extra_args: list[str] | None = None,
) -> TestResult:
    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
        *(extra_args or []),
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)
    tgt = rule_runner.get_target(Address(spec_path=spec_path, target_name=target_name, relative_file_path=relative_file_path))
    return rule_runner.request(
        TestResult,
        [ClojureTestRequest.Batch("", (ClojureTestFieldSet.create(tgt),), None)],
    )


def test_simple_passing_test(rule_runner: RuleRunner) -> None:
    """Test that a simple passing test succeeds."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example_test.clj": dedent(
                """\
                (ns example-test
                  (:require [clojure.test :refer [deftest is testing]]))

                (deftest test-addition
                  (testing "Basic addition"
                    (is (= 4 (+ 2 2)))
                    (is (= 0 (+ -1 1)))))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "example_test.clj")

    assert result.exit_code == 0
    stdout_text = result.stdout_bytes.decode()
    assert "test-addition" in stdout_text or "example-test" in stdout_text


def test_simple_failing_test(rule_runner: RuleRunner) -> None:
    """Test that a failing test returns non-zero exit code."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "failure_test.clj": dedent(
                """\
                (ns failure-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-failure
                  (is (= 5 (+ 2 2)) "2 + 2 should equal 4, not 5"))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "failure_test.clj")

    assert result.exit_code != 0
    output = (result.stdout_bytes + result.stderr_bytes).decode()
    assert "FAIL" in output or "failed" in output.lower()


def test_test_with_timeout(rule_runner: RuleRunner) -> None:
    """Test that timeout field is respected."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    timeout=120,
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "timeout_test.clj": dedent(
                """\
                (ns timeout-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-quick
                  (is (= 4 (+ 2 2))))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "timeout_test.clj")

    # Should succeed (not timeout)
    assert result.exit_code == 0


def test_test_with_clojure_source_dependencies(rule_runner: RuleRunner) -> None:
    """Test that tests can depend on clojure_source targets."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_source(
                    name='lib',
                    source='calculator.clj',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )

                clojure_tests(
                    name='tests',
                    dependencies=[
                        ':lib',
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "calculator.clj": dedent(
                """\
                (ns calculator)

                (defn add [a b]
                  (+ a b))

                (defn multiply [a b]
                  (* a b))
                """
            ),
            "calculator_test.clj": dedent(
                """\
                (ns calculator-test
                  (:require [clojure.test :refer [deftest is testing]]
                            [calculator :as calc]))

                (deftest test-calculator
                  (testing "Addition"
                    (is (= 5 (calc/add 2 3)))
                    (is (= 0 (calc/add -1 1))))
                  (testing "Multiplication"
                    (is (= 6 (calc/multiply 2 3)))
                    (is (= 0 (calc/multiply 5 0)))))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "calculator_test.clj")

    # Test should pass - verifies clojure_source dependencies work
    assert result.exit_code == 0


def test_test_failure_with_assertion_message(rule_runner: RuleRunner) -> None:
    """Test that assertion failure messages appear in output."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "assertion_test.clj": dedent(
                """\
                (ns assertion-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-with-custom-message
                  (is (= 100 (* 10 11)) "Expected 10 * 11 to equal 100"))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "assertion_test.clj")

    assert result.exit_code != 0
    output = (result.stdout_bytes + result.stderr_bytes).decode()
    # Verify failure message contains the custom assertion message
    assert "Expected 10 * 11 to equal 100" in output or "expected" in output.lower()


def test_test_with_extra_env_vars(rule_runner: RuleRunner) -> None:
    """Test that extra_env_vars field passes environment variables to tests."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_test(
                    name='tests',
                    source='env_test.clj',
                    extra_env_vars=['TEST_VAR=test_value', 'ANOTHER_VAR=42'],
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "env_test.clj": dedent(
                """\
                (ns env-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-environment-variables
                  (is (= "test_value" (System/getenv "TEST_VAR"))
                      "TEST_VAR should be set to test_value")
                  (is (= "42" (System/getenv "ANOTHER_VAR"))
                      "ANOTHER_VAR should be set to 42"))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "env_test.clj")

    assert result.exit_code == 0


def test_test_with_global_extra_env_vars(rule_runner: RuleRunner) -> None:
    """Test that [test].extra_env_vars passes environment variables to tests."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_test(
                    name='tests',
                    source='env_test.clj',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "env_test.clj": dedent(
                """\
                (ns env-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-global-env-var
                  (is (= "global_value" (System/getenv "GLOBAL_TEST_VAR"))
                      "GLOBAL_TEST_VAR should be set via [test].extra_env_vars"))
                """
            ),
        }
    )

    result = run_clojure_test(
        rule_runner,
        "tests",
        "env_test.clj",
        extra_args=["--test-extra-env-vars=['GLOBAL_TEST_VAR=global_value']"],
    )

    assert result.exit_code == 0


def test_missing_namespace_declaration_fails(rule_runner: RuleRunner) -> None:
    """Test that missing namespace declaration produces clear error message."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "no_namespace_test.clj": dedent(
                """\
                ; Missing (ns ...) declaration
                (require '[clojure.test :refer [deftest is]])

                (deftest test-something
                  (is (= 4 (+ 2 2))))
                """
            ),
        }
    )

    # The ValueError is raised within the Pants rule engine, which catches it
    # and reports it as an execution error. So we check that the test fails.
    try:
        result = run_clojure_test(rule_runner, "tests", "no_namespace_test.clj")
        # If we get here, the test ran but should have failed
        assert False, "Expected test execution to fail due to missing namespace"
    except Exception as e:
        # Verify the error message is helpful
        error_str = str(e)
        assert "namespace" in error_str.lower() or "ns" in error_str.lower()


def test_syntax_error_in_test_fails_with_message(rule_runner: RuleRunner) -> None:
    """Test that syntax errors in test files produce clear error messages."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "syntax_error_test.clj": dedent(
                """\
                (ns syntax-error-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-with-syntax-error
                  ; Missing closing parenthesis
                  (is (= 4 (+ 2 2))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "syntax_error_test.clj")

    # Syntax errors should cause non-zero exit
    assert result.exit_code != 0
    output = (result.stdout_bytes + result.stderr_bytes).decode()
    # Verify error message mentions syntax/EOF/parsing issue
    assert any(keyword in output.lower() for keyword in ["eof", "syntax", "unexpected", "parse", "read"])


def test_namespace_with_metadata_passes(rule_runner: RuleRunner) -> None:
    """Test that the test runner handles metadata on the ns form."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.3.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
                serialized_bytes_length = 4230055
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.3"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example_metadata_test.clj": dedent(
                """\
                (ns ^{:doc "Tests with metadata on ns form."}
                  example-metadata-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-with-metadata-ns
                  (is (= 1 1)))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "example_metadata_test.clj")

    assert result.exit_code == 0


def test_file_target_available_in_sandbox(rule_runner: RuleRunner) -> None:
    """Test that a file() target dependency is available in the test sandbox."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": CLOJURE_3RDPARTY_BUILD,
            "3rdparty/jvm/default.lock": CLOJURE_LOCKFILE,
            "data/BUILD": dedent(
                """\
                file(name="test-data", source="test-data.txt")
                """
            ),
            "data/test-data.txt": "hello world",
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                        'data:test-data',
                    ],
                )
                """
            ),
            "file_test.clj": dedent(
                """\
                (ns file-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest read-file-test
                  (is (= "hello world" (slurp "data/test-data.txt"))))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "file_test.clj")

    assert result.exit_code == 0


def test_files_generator_available_in_sandbox(rule_runner: RuleRunner) -> None:
    """Test that a files() generator target dependency is available in the test sandbox."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": CLOJURE_3RDPARTY_BUILD,
            "3rdparty/jvm/default.lock": CLOJURE_LOCKFILE,
            "data/BUILD": dedent(
                """\
                files(name="test-data", sources=["*.txt"])
                """
            ),
            "data/file1.txt": "content one",
            "data/file2.txt": "content two",
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                        'data:test-data',
                    ],
                )
                """
            ),
            "files_test.clj": dedent(
                """\
                (ns files-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest read-files-test
                  (is (= "content one" (slurp "data/file1.txt")))
                  (is (= "content two" (slurp "data/file2.txt"))))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "files_test.clj")

    assert result.exit_code == 0
