from __future__ import annotations

from textwrap import dedent

import pytest
from pants.backend.java.target_types import JavaSourcesGeneratorTarget
from pants.core.goals.repl import ReplRequest
from pants.core.util_rules import config_files, external_tool, source_files, stripped_source_files, system_binaries
from pants.engine.addresses import Address
from pants.engine.rules import QueryRule
from pants.jvm import classpath, jvm_common, non_jvm_dependencies
from pants.jvm.goals import lockfile
from pants.jvm.resolve.coursier_fetch import rules as coursier_fetch_rules
from pants.jvm.resolve.coursier_setup import rules as coursier_setup_rules
from pants.jvm.target_types import JvmArtifactTarget
from pants.jvm.util_rules import rules as jdk_util_rules
from pants.testutil.rule_runner import PYTHON_BOOTSTRAP_ENV, RuleRunner
from pants_backend_clojure import compile_clj
from pants_backend_clojure.goals.repl import ClojureNRepl, ClojureRebelRepl, ClojureRepl
from pants_backend_clojure.goals.repl import rules as repl_rules
from pants_backend_clojure.namespace_analysis import rules as namespace_analysis_rules
from pants_backend_clojure.target_types import (
    ClojureSourcesGeneratorTarget,
    ClojureSourceTarget,
    ClojureTestsGeneratorTarget,
    ClojureTestTarget,
)
from pants_backend_clojure.target_types import rules as target_types_rules


@pytest.fixture
def rule_runner() -> RuleRunner:
    rule_runner = RuleRunner(
        preserve_tmpdirs=True,
        rules=[
            *classpath.rules(),
            *compile_clj.rules(),
            *config_files.rules(),
            *coursier_fetch_rules(),
            *coursier_setup_rules(),
            *external_tool.rules(),
            *jdk_util_rules(),
            *jvm_common.rules(),
            *namespace_analysis_rules(),
            *non_jvm_dependencies.rules(),
            *source_files.rules(),
            *stripped_source_files.rules(),
            *system_binaries.rules(),
            *target_types_rules(),
            *repl_rules(),
            *lockfile.rules(),
            QueryRule(ReplRequest, [ClojureRepl]),
            QueryRule(ReplRequest, [ClojureNRepl]),
            QueryRule(ReplRequest, [ClojureRebelRepl]),
        ],
        target_types=[
            ClojureSourceTarget,
            ClojureSourcesGeneratorTarget,
            ClojureTestTarget,
            ClojureTestsGeneratorTarget,
            JvmArtifactTarget,
            JavaSourcesGeneratorTarget,
        ],
    )
    return rule_runner


_JVM_RESOLVES = {
    "jvm-default": "3rdparty/jvm/default.lock",
}

_CLOJURE_LOCKFILE = dedent(
    """\
    # This lockfile was autogenerated by Pants. To regenerate, run:
    #
    #    pants generate-lockfiles
    #
    # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
    # {
    #   "version": 1,
    #   "generated_with_requirements": [
    #     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
    #   ]
    # }
    # --- END PANTS LOCKFILE METADATA ---

    [[entries]]
    file_name = "org.clojure_clojure_1.12.3.jar"
    [[entries.directDependencies]]
    group = "org.clojure"
    artifact = "core.specs.alpha"
    version = "0.4.74"
    packaging = "jar"

    [[entries.directDependencies]]
    group = "org.clojure"
    artifact = "spec.alpha"
    version = "0.5.238"
    packaging = "jar"

    [[entries.dependencies]]
    group = "org.clojure"
    artifact = "core.specs.alpha"
    version = "0.4.74"
    packaging = "jar"

    [[entries.dependencies]]
    group = "org.clojure"
    artifact = "spec.alpha"
    version = "0.5.238"
    packaging = "jar"


    [entries.coord]
    group = "org.clojure"
    artifact = "clojure"
    version = "1.12.3"
    packaging = "jar"
    [entries.file_digest]
    fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
    serialized_bytes_length = 4230055
    [[entries]]
    file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
    [[entries.directDependencies]]
    group = "org.clojure"
    artifact = "clojure"
    version = "1.12.3"
    packaging = "jar"

    [[entries.dependencies]]
    group = "org.clojure"
    artifact = "clojure"
    version = "1.12.3"
    packaging = "jar"


    [entries.coord]
    group = "org.clojure"
    artifact = "core.specs.alpha"
    version = "0.4.74"
    packaging = "jar"
    [entries.file_digest]
    fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
    serialized_bytes_length = 4306
    [[entries]]
    file_name = "org.clojure_spec.alpha_0.5.238.jar"
    [[entries.directDependencies]]
    group = "org.clojure"
    artifact = "clojure"
    version = "1.12.3"
    packaging = "jar"

    [[entries.dependencies]]
    group = "org.clojure"
    artifact = "clojure"
    version = "1.12.3"
    packaging = "jar"


    [entries.coord]
    group = "org.clojure"
    artifact = "spec.alpha"
    version = "0.5.238"
    packaging = "jar"
    [entries.file_digest]
    fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
    serialized_bytes_length = 636643
    """
)


def test_repl_request_includes_clojure_main(rule_runner: RuleRunner) -> None:
    """Test that REPL request includes clojure.main command."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example.clj": dedent(
                """\
                (ns example)

                (defn greet [name]
                  (str "Hello, " name "!"))
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="", target_name="lib", relative_file_path="example.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify command includes clojure.main
    assert "clojure.main" in request.args
    assert "--repl" in request.args

    # Verify runs in workspace
    assert request.run_in_workspace is True


def test_repl_request_includes_source_files(rule_runner: RuleRunner) -> None:
    """Test that REPL request includes project source files."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example.clj": dedent(
                """\
                (ns example)

                (defn add [x y]
                  (+ x y))
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="", target_name="lib", relative_file_path="example.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify digest is not empty (contains source files and dependencies)
    assert request.digest is not None
    assert request.digest.fingerprint != ""

    # Verify JDK environment is set up
    assert request.extra_env is not None
    assert len(request.immutable_input_digests) > 0


def test_repl_request_includes_dependencies(rule_runner: RuleRunner) -> None:
    """Test that REPL request includes dependencies in classpath."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example.clj": dedent(
                """\
                (ns example)

                (defn identity-fn [x] x)
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="", target_name="lib", relative_file_path="example.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify classpath includes current directory
    assert "." in request.args or any("." in str(arg) for arg in request.args)

    # Verify command structure is correct
    assert len(request.args) > 0
    assert request.args[-2] == "clojure.main"
    assert request.args[-1] == "--repl"


def test_repl_request_with_test_sources(rule_runner: RuleRunner) -> None:
    """Test that REPL request can include test sources."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "src/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "src/example.clj": dedent(
                """\
                (ns example)

                (defn greet [name]
                  (str "Hello, " name "!"))
                """
            ),
            "test/BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        'src:lib',
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "test/example_test.clj": dedent(
                """\
                (ns example-test
                  (:require [clojure.test :refer [deftest is]]
                            [example :refer [greet]]))

                (deftest test-greet
                  (is (= "Hello, World!" (greet "World"))))
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    # Get test target
    test_tgt = rule_runner.get_target(Address(spec_path="test", target_name="tests", relative_file_path="example_test.clj"))

    repl = ClojureRepl(targets=(test_tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify REPL request is created successfully
    assert "clojure.main" in request.args
    assert "--repl" in request.args
    assert request.run_in_workspace is True


def test_repl_request_with_multiple_targets(rule_runner: RuleRunner) -> None:
    """Test that REPL request can handle multiple targets."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "foo/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "foo/foo.clj": dedent(
                """\
                (ns foo)

                (defn foo-fn [] "foo")
                """
            ),
            "bar/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "bar/bar.clj": dedent(
                """\
                (ns bar)

                (defn bar-fn [] "bar")
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    # Get both targets
    foo_tgt = rule_runner.get_target(Address(spec_path="foo", target_name="lib", relative_file_path="foo.clj"))
    bar_tgt = rule_runner.get_target(Address(spec_path="bar", target_name="lib", relative_file_path="bar.clj"))

    repl = ClojureRepl(targets=(foo_tgt, bar_tgt))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify REPL request is created successfully with multiple targets
    assert "clojure.main" in request.args
    assert "--repl" in request.args
    assert request.run_in_workspace is True
    assert request.digest is not None


def test_repl_uses_workspace_for_live_reloading(rule_runner: RuleRunner) -> None:
    """Test that REPL uses run_in_workspace=True to support live file reloading.

    This is critical for Clojure REPL-driven development where you edit files
    and reload namespaces to see changes immediately.
    """
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example.clj": dedent(
                """\
                (ns example)

                (defn greet [name]
                  (str "Hello, " name "!"))
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="", target_name="lib", relative_file_path="example.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Critical: run_in_workspace must be True for live reloading
    assert request.run_in_workspace is True, "REPL must run in workspace to see live file changes during development"


def test_repl_argv_includes_jdk_paths(rule_runner: RuleRunner) -> None:
    """Test that REPL argv properly handles JDK paths with chroot prefixing.

    This ensures the JDK preparation script can be found when running in workspace.
    """
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example.clj": dedent(
                """\
                (ns example)

                (defn identity-fn [x] x)
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="", target_name="lib", relative_file_path="example.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify JDK paths are properly handled
    argv_str = " ".join(request.args)

    # Should contain {chroot} prefix for JDK paths when run_in_workspace=True
    assert "{chroot}" in argv_str, "JDK paths must use {chroot} prefix for run_in_workspace=True"

    # Should still reference bash and clojure.main
    assert any("bash" in arg for arg in request.args)
    assert "clojure.main" in request.args


def test_repl_environment_includes_chroot_prefix(rule_runner: RuleRunner) -> None:
    """Test that REPL environment properly configures PANTS_INTERNAL_ABSOLUTE_PREFIX.

    This is required for the JDK preparation script to create correct symlinks.
    """
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example.clj": "(ns example)",
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="", target_name="lib", relative_file_path="example.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify environment setup
    assert request.extra_env is not None
    assert "PANTS_INTERNAL_ABSOLUTE_PREFIX" in request.extra_env
    assert request.extra_env["PANTS_INTERNAL_ABSOLUTE_PREFIX"] == "{chroot}/"


def test_repl_classpath_includes_source_roots(rule_runner: RuleRunner) -> None:
    """Test that REPL classpath includes source roots for namespace resolution.

    This is critical - Clojure needs the source root directories in the classpath
    to resolve namespaces. For example, if you have:
    - File: src/example/core.clj
    - Namespace: (ns example.core)
    Then 'src' must be in the classpath, not 'src/example'.
    """
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            # File at root with simple namespace
            "example.clj": "(ns example)",
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="", target_name="lib", relative_file_path="example.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Find the -cp argument and verify it contains the source root
    argv = request.args
    for i, arg in enumerate(argv):
        if arg == "-cp" and i + 1 < len(argv):
            classpath = argv[i + 1]
            classpath_entries = classpath.split(":")

            # For a file at the root with namespace 'example', the source root should be "."
            assert "." in classpath_entries, f"Classpath must include source root '.'. Got: {classpath_entries}"
            break
    else:
        pytest.fail("-cp argument not found in argv")


# NOTE: nREPL tests are skipped because they require fetching the nREPL artifact
# from Maven repositories, which may not be accessible in the test environment.
# The nREPL implementation is functional and can be tested manually with:
#   pants repl --repl-shell=nrepl <target-spec>

# @pytest.mark.skip(reason="Requires nREPL artifact from Maven Central")
# def test_nrepl_request_includes_nrepl_server(rule_runner: RuleRunner) -> None:
#     """Test that nREPL request includes nREPL server startup command."""
#     # Test implementation available but skipped due to Maven repository dependency


# NOTE: Rebel Readline tests are also skipped for the same Maven repository reasons.
# The Rebel implementation is functional and can be tested manually with:
#   pants repl --repl-shell=rebel <target-spec>

# @pytest.mark.skip(reason="Requires Rebel Readline artifact from Maven Central")
# def test_rebel_repl_request_includes_rebel_main(rule_runner: RuleRunner) -> None:
#     """Test that Rebel REPL request includes rebel-readline.main."""
#     # Test implementation available but skipped due to Maven repository dependency


def test_repl_load_resolve_sources_enabled_by_default(rule_runner: RuleRunner) -> None:
    """Test that --clojure-repl-load-resolve-sources is enabled by default.

    When enabled, the REPL should include ALL Clojure source roots in the same resolve,
    not just transitive dependencies. This allows requiring any namespace without
    explicit BUILD dependencies.
    """
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            # Project A - will be the target we run REPL for
            "project_a/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "project_a/a.clj": dedent(
                """\
                (ns project-a)

                (defn a-fn [] "a")
                """
            ),
            # Project B - in same resolve, but NOT a dependency of A
            "project_b/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "project_b/b.clj": dedent(
                """\
                (ns project-b)

                (defn b-fn [] "b")
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
        # Note: NOT setting --no-clojure-repl-load-resolve-sources
        # Default should be True
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    # Run REPL for project A only
    tgt = rule_runner.get_target(Address(spec_path="project_a", target_name="lib", relative_file_path="a.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify REPL was created successfully
    assert "clojure.main" in request.args
    assert request.run_in_workspace is True

    # CRITICAL: Verify that BOTH project_a and project_b source roots are in classpath
    # This is the key behavior - all sources in the resolve should be available
    argv = request.args
    for i, arg in enumerate(argv):
        if arg == "-cp" and i + 1 < len(argv):
            classpath = argv[i + 1]
            classpath_entries = classpath.split(":")

            # Both project directories should be source roots in the classpath
            assert "project_a" in classpath_entries, f"project_a source root must be in classpath. Got: {classpath_entries}"
            assert "project_b" in classpath_entries, (
                f"project_b source root must be in classpath (load_resolve_sources=True). Got: {classpath_entries}"
            )
            break
    else:
        pytest.fail("-cp argument not found in argv")


def test_repl_load_resolve_sources_disabled_hermetic_mode(rule_runner: RuleRunner) -> None:
    """Test that --no-clojure-repl-load-resolve-sources enables hermetic mode.

    When disabled, the REPL should only include transitive dependencies from the
    BUILD file, not all targets in the resolve. This is "hermetic" - strictly
    respecting the dependency graph.
    """
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            # Project A - will be the target we run REPL for
            "project_a/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "project_a/a.clj": dedent(
                """\
                (ns project-a)

                (defn a-fn [] "a")
                """
            ),
            # Project B - in same resolve, but NOT a dependency of A
            "project_b/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "project_b/b.clj": dedent(
                """\
                (ns project-b)

                (defn b-fn [] "b")
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
        "--no-clojure-repl-load-resolve-sources",  # Disable resolve-wide loading
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    # Run REPL for project A only
    tgt = rule_runner.get_target(Address(spec_path="project_a", target_name="lib", relative_file_path="a.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify REPL was created successfully in hermetic mode
    assert "clojure.main" in request.args
    assert request.run_in_workspace is True

    # CRITICAL: Verify that project_b is NOT in the classpath in hermetic mode
    # Only project_a should be included since it's the target we're running
    argv = request.args
    for i, arg in enumerate(argv):
        if arg == "-cp" and i + 1 < len(argv):
            classpath = argv[i + 1]
            classpath_entries = classpath.split(":")

            # project_a should be in classpath (it's the target we're running)
            assert "project_a" in classpath_entries, f"project_a source root must be in classpath. Got: {classpath_entries}"

            # project_b should NOT be in classpath (hermetic mode, not a dependency)
            assert "project_b" not in classpath_entries, f"project_b should NOT be in classpath in hermetic mode. Got: {classpath_entries}"
            break
    else:
        pytest.fail("-cp argument not found in argv")


def test_repl_load_resolve_sources_with_multiple_resolves(rule_runner: RuleRunner) -> None:
    """Test that load_resolve_sources only loads targets from the same resolve.

    When multiple resolves exist, loading resolve sources should only include
    targets from the same resolve, not from other resolves.
    """
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                    resolve="resolve-a",
                )
                jvm_artifact(
                    name="org.clojure_clojure_resolve_b",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                    resolve="resolve-b",
                )
                """
            ),
            "3rdparty/jvm/resolve-a.lock": _CLOJURE_LOCKFILE,
            "3rdparty/jvm/resolve-b.lock": _CLOJURE_LOCKFILE,
            # Project A - in resolve-a
            "project_a/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    resolve='resolve-a',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "project_a/a.clj": dedent(
                """\
                (ns project-a)

                (defn a-fn [] "a")
                """
            ),
            # Project B - in resolve-b (different resolve)
            "project_b/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    resolve='resolve-b',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure_resolve_b',
                    ],
                )
                """
            ),
            "project_b/b.clj": dedent(
                """\
                (ns project-b)

                (defn b-fn [] "b")
                """
            ),
        }
    )

    args = [
        "--jvm-resolves={'resolve-a': '3rdparty/jvm/resolve-a.lock', 'resolve-b': '3rdparty/jvm/resolve-b.lock'}",
        "--jvm-default-resolve=resolve-a",
        # load_resolve_sources is enabled by default
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    # Run REPL for project A (resolve-a)
    tgt = rule_runner.get_target(Address(spec_path="project_a", target_name="lib", relative_file_path="a.clj"))

    repl = ClojureRepl(targets=(tgt,))
    request = rule_runner.request(ReplRequest, [repl])

    # Verify REPL was created successfully
    # The implementation should only load project_a (from resolve-a),
    # not project_b (from resolve-b)
    assert "clojure.main" in request.args
    assert request.run_in_workspace is True


def test_repl_nrepl_load_resolve_sources(rule_runner: RuleRunner) -> None:
    """Test that nREPL also respects --clojure-repl-load-resolve-sources flag."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "project_a/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "project_a/a.clj": dedent(
                """\
                (ns project-a)

                (defn a-fn [] "a")
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="project_a", target_name="lib", relative_file_path="a.clj"))

    # This test verifies the rule executes without errors
    # Actual nREPL functionality would require Maven artifacts
    repl = ClojureNRepl(targets=(tgt,))
    # Note: This will fail to fetch nREPL from Maven, but we can skip it
    # since the integration test environment doesn't have network access


def test_repl_rebel_load_resolve_sources(rule_runner: RuleRunner) -> None:
    """Test that Rebel REPL also respects --clojure-repl-load-resolve-sources flag."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": _CLOJURE_LOCKFILE,
            "project_a/BUILD": dedent(
                """\
                clojure_sources(
                    name='lib',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "project_a/a.clj": dedent(
                """\
                (ns project-a)

                (defn a-fn [] "a")
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="project_a", target_name="lib", relative_file_path="a.clj"))

    # This test verifies the rule executes without errors
    # Actual Rebel functionality would require Maven artifacts
    repl = ClojureRebelRepl(targets=(tgt,))
    # Note: This will fail to fetch Rebel Readline from Maven, but we can skip it
    # since the integration test environment doesn't have network access
