"""Regression tests for the check goal hang caused by nested await Get() calls.

The root cause was nested `await Get()` in check.py and aot_compile.py which
violated the Pants Engine's async patterns, causing scheduler deadlocks.
"""

from __future__ import annotations

from textwrap import dedent

import pytest

from pants_backend_clojure.goals.check import ClojureCheckFieldSet, ClojureCheckRequest
from pants_backend_clojure.goals import check as check_goal
from pants_backend_clojure.namespace_analysis import rules as namespace_analysis_rules
from pants_backend_clojure.target_types import (
    ClojureSourceTarget,
)
from pants_backend_clojure.target_types import rules as target_types_rules
from pants_backend_clojure import compile_clj
from pants.core.goals.check import CheckResults
from pants.core.util_rules import config_files, external_tool, source_files, stripped_source_files, system_binaries
from pants.engine.addresses import Address
from pants.jvm import classpath, jvm_common, non_jvm_dependencies
from pants.jvm.goals import lockfile
from pants.jvm.resolve.coursier_fetch import rules as coursier_fetch_rules
from pants.jvm.resolve.coursier_setup import rules as coursier_setup_rules
from pants.jvm.target_types import JvmArtifactTarget
from pants.jvm.util_rules import rules as jdk_util_rules
from pants.testutil.rule_runner import PYTHON_BOOTSTRAP_ENV, QueryRule, RuleRunner
from pants.jvm.classpath import Classpath
from pants.engine.addresses import Addresses


# Lockfile with Clojure 1.12.3 and correct fingerprints
LOCKFILE_WITH_CLOJURE = """\
# This lockfile was autogenerated by Pants. To regenerate, run:
#
#    pants generate-lockfiles
#
# --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
# {
#   "version": 1,
#   "generated_with_requirements": [
#     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
#   ]
# }
# --- END PANTS LOCKFILE METADATA ---

[[entries]]
file_name = "org.clojure_clojure_1.12.3.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"

[[entries.directDependencies]]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"
[entries.file_digest]
fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
serialized_bytes_length = 4230055
[[entries]]
file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"
[entries.file_digest]
fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
serialized_bytes_length = 4306
[[entries]]
file_name = "org.clojure_spec.alpha_0.5.238.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"
[entries.file_digest]
fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
serialized_bytes_length = 636643
"""


@pytest.fixture
def rule_runner() -> RuleRunner:
    """Create a minimal rule runner for hang reproduction."""
    rule_runner = RuleRunner(
        preserve_tmpdirs=True,
        rules=[
            *classpath.rules(),
            *compile_clj.rules(),
            *config_files.rules(),
            *coursier_fetch_rules(),
            *coursier_setup_rules(),
            *external_tool.rules(),
            *jdk_util_rules(),
            *jvm_common.rules(),
            *namespace_analysis_rules(),
            *non_jvm_dependencies.rules(),
            *source_files.rules(),
            *stripped_source_files.rules(),
            *system_binaries.rules(),
            *target_types_rules(),
            *check_goal.rules(),
            *lockfile.rules(),
            QueryRule(CheckResults, [ClojureCheckRequest]),
            QueryRule(Classpath, [Addresses]),
        ],
        target_types=[
            ClojureSourceTarget,
            JvmArtifactTarget,
        ],
    )
    return rule_runner


_JVM_RESOLVES = {
    "jvm-default": "3rdparty/jvm/default.lock",
}


def test_check_does_not_hang_with_clojure_dependency(rule_runner: RuleRunner) -> None:
    """Verify that check goal completes when source depends on jvm_artifact(clojure)."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": LOCKFILE_WITH_CLOJURE,
            "BUILD": 'clojure_source(name="example", source="example.clj", dependencies=["3rdparty/jvm:org.clojure_clojure"])',
            "example.clj": dedent(
                """\
                (ns example)
                (defn greet [name]
                  (str "Hello, " name))
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)
    tgt = rule_runner.get_target(
        Address(spec_path="", target_name="example")
    )
    field_set = ClojureCheckFieldSet.create(tgt)

    # This is where the hang occurs
    results = rule_runner.request(
        CheckResults,
        [ClojureCheckRequest([field_set])],
    )

    assert len(results.results) == 1
    assert results.results[0].exit_code == 0


def test_check_does_not_hang_with_target_creation_only(rule_runner: RuleRunner) -> None:
    """Verify that target creation alone does not hang."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": LOCKFILE_WITH_CLOJURE,
            "BUILD": 'clojure_source(name="example", source="example.clj", dependencies=["3rdparty/jvm:org.clojure_clojure"])',
            "example.clj": dedent(
                """\
                (ns example)
                (defn greet [name]
                  (str "Hello, " name))
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    tgt = rule_runner.get_target(Address(spec_path="", target_name="example"))
    assert tgt is not None


def test_check_does_not_hang_with_classpath_resolution(rule_runner: RuleRunner) -> None:
    """Verify that classpath resolution alone does not hang."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": LOCKFILE_WITH_CLOJURE,
            "BUILD": 'clojure_source(name="example", source="example.clj", dependencies=["3rdparty/jvm:org.clojure_clojure"])',
            "example.clj": dedent(
                """\
                (ns example)
                (defn greet [name]
                  (str "Hello, " name))
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)

    classpath = rule_runner.request(
        Classpath,
        [Addresses([Address(spec_path="", target_name="example")])]
    )
    assert classpath is not None


def test_check_does_not_hang_without_artifact_dependency(rule_runner: RuleRunner) -> None:
    """Verify that check goal completes when source has no jvm_artifact dependency."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.3",
                )
                """
            ),
            "3rdparty/jvm/default.lock": LOCKFILE_WITH_CLOJURE,
            # NOTE: No dependencies field - no jvm_artifact dependency
            "BUILD": 'clojure_source(name="example", source="example.clj")',
            "example.clj": dedent(
                """\
                (ns example)
                (defn greet [name]
                  (str "Hello, " name))
                """
            ),
        }
    )

    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)
    tgt = rule_runner.get_target(Address(spec_path="", target_name="example"))
    field_set = ClojureCheckFieldSet.create(tgt)

    results = rule_runner.request(
        CheckResults,
        [ClojureCheckRequest([field_set])],
    )

    assert len(results.results) == 1
